//! Build script: generates `bundled_themes.rs` containing the
//! `BUNDLED_THEMES` array from every `.toml` file under `themes/`.
//!
//! The generated array preserves the contract that `default.toml`
//! is first (used as the panic-safe fallback if a named theme can't
//! be found); the remaining themes are emitted in case-insensitive
//! alphabetical order.
//!
//! Re-runs only when the contents of `themes/` change.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let themes_dir = PathBuf::from("themes");
    println!("cargo:rerun-if-changed=themes");

    let entries =
        fs::read_dir(&themes_dir).expect("themes/ must exist and be readable at build time");
    let mut names: Vec<String> = entries
        .filter_map(|e| e.ok())
        .filter_map(|e| {
            let path = e.path();
            if path.extension().and_then(|s| s.to_str()) != Some("toml") {
                return None;
            }
            let stem = path.file_stem()?.to_str()?.to_string();
            Some(stem)
        })
        .collect();
    names.sort_by_key(|n| n.to_ascii_lowercase());

    // `default` always lands first so `BUNDLED_THEMES.first()` is the
    // canonical fallback. Then the rest in alphabetical order. If
    // `default.toml` is missing the build fails loudly.
    let default_pos = names
        .iter()
        .position(|n| n == "default")
        .expect("themes/default.toml is required (used as panic-safe fallback)");
    let default = names.remove(default_pos);
    names.insert(0, default);

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by cargo");
    let manifest_dir = PathBuf::from(manifest_dir);

    let mut src = String::new();
    src.push_str("// AUTO-GENERATED by build.rs from themes/. Do not edit.\n");
    src.push_str("const BUNDLED_THEMES: &[BundledTheme] = &[\n");
    for name in &names {
        let abs_path = manifest_dir.join("themes").join(format!("{name}.toml"));
        let abs_path_str = abs_path.to_string_lossy().replace('\\', "/");
        src.push_str(&format!(
            "    BundledTheme {{ name: {name:?}, content: include_str!({abs_path_str:?}) }},\n",
        ));
    }
    src.push_str("];\n\n");

    src.push_str("/// Names of every bundled theme, in `BUNDLED_THEMES` order.\n");
    src.push_str("pub const THEME_NAMES: &[&str] = &[\n");
    for name in &names {
        src.push_str(&format!("    {name:?},\n"));
    }
    src.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set by cargo");
    let dest = PathBuf::from(out_dir).join("bundled_themes.rs");
    fs::write(&dest, src).expect("write generated bundled_themes.rs");
}
