//! Per-key options-menu help text.
//!
//! Each entry in the options menu shows a multi-line description in
//! its right-hand panel when focused. This module is the single
//! source of truth for that text — extracted from `config.rs` so
//! that `config.rs` carries the schema (field types, names,
//! validation) and `menu/` carries the UI text the menu renders.
//!
//! Each entry is one rendered line; an empty string is a blank
//! separator line. Line 0 is rendered bold + title-coloured; lines
//! 1+ are rendered in the main foreground colour.
//!
//! Rule of thumb: if you change a config key's user-visible
//! semantics, update its entry here so the in-app help reflects
//! the new behaviour.

use crate::config::ConfigKey;

/// Returns the multi-line help text for a config key as it appears
/// in the right-hand panel of the options menu.
pub fn desc(key: ConfigKey) -> &'static [&'static str] {
    match key {
        ConfigKey::ThemeBackground => &[
            "Render the theme background.",
            "",
            "Off lets the terminal background show",
            "through, useful for transparent terminals.",
            "",
            "Default: on.",
        ],
        ConfigKey::RoundedCorners => &[
            "Rounded widget corners.",
            "",
            "Off uses square corners.",
            "",
            "Default: on.",
        ],
        ConfigKey::ProcReversed => &[
            "Reverse sort order.",
            "",
            "Flips the sort direction. The 'r' key on the",
            "process widget toggles this at runtime.",
            "",
            "Default: off.",
        ],
        ConfigKey::ProcTree => &[
            "Tree view.",
            "",
            "Group processes under their parent with",
            "indented branches. The 'e' key on the",
            "process widget toggles this at runtime.",
            "",
            "Default: off.",
        ],
        ConfigKey::ProcColors => &[
            "Color process rows by CPU usage.",
            "",
            "Higher-CPU rows take a warmer color so they",
            "stand out at a glance.",
            "",
            "Default: on.",
        ],
        ConfigKey::ProcGradient => &[
            "Fade process rows by distance.",
            "",
            "Rows farther from the selected process fade",
            "toward the background color, focusing",
            "attention near the cursor.",
            "",
            "Default: on.",
        ],
        ConfigKey::ProcPerCore => &[
            "Per-core CPU percentage.",
            "",
            "Show each process's CPU usage relative to a",
            "single core. Values can exceed 100% on",
            "multi-threaded workloads. Off divides usage",
            "across all cores, capping the total at 100%.",
            "",
            "Default: off.",
        ],
        ConfigKey::ProcMemBytes => &[
            "Memory as bytes.",
            "",
            "Show process memory in bytes (GB / MB / KB)",
            "instead of percentage of total memory.",
            "",
            "Default: on.",
        ],
        ConfigKey::ProcAggregate => &[
            "Aggregate child resources in tree view.",
            "",
            "Each parent's CPU and memory totals include",
            "every descendant. Has no effect outside Tree",
            "View.",
            "",
            "Default: off.",
        ],
        ConfigKey::KeepDeadProcUsage => &[
            "Preserve last value for ended processes.",
            "",
            "Show each terminated process's last CPU and",
            "memory reading until it disappears from the",
            "list, instead of showing zero.",
            "",
            "Default: on.",
        ],
        ConfigKey::CpuInvertLower => &[
            "Mirror the lower graph.",
            "",
            "Flips the lower graph upside-down so it",
            "grows downward, mirroring the upper graph.",
            "Has no effect when CPU Single Graph is on.",
            "",
            "Default: on.",
        ],
        ConfigKey::CpuSingleGraph => &[
            "Show one CPU graph instead of two.",
            "",
            "Hides the lower CPU graph and gives the",
            "upper graph the full vertical space.",
            "",
            "Default: off.",
        ],
        ConfigKey::CpuAutoScale => &[
            "Auto-scale CPU graph y-axis.",
            "",
            "Scales each graph to its largest visible",
            "value. Off uses a fixed 0–100% scale so bar",
            "height matches the percentage.",
            "",
            "Default: off.",
        ],
        ConfigKey::ShowUptime => &[
            "Show system uptime.",
            "",
            "Adds the time since boot to the CPU widget",
            "header.",
            "",
            "Default: on.",
        ],
        ConfigKey::ShowCpuWatts => &[
            "Show CPU power draw.",
            "",
            "Adds a wattage meter to the CPU widget.",
            "Requires PawnIO and Administrator",
            "privileges.",
            "",
            "Default: on.",
        ],
        ConfigKey::CheckTemp => &[
            "Read CPU temperature.",
            "",
            "Requires PawnIO and Administrator",
            "privileges. Without those, temperature stays",
            "unavailable even when on.",
            "",
            "Default: on.",
        ],
        ConfigKey::ShowCoretemp => &[
            "Per-core temperatures.",
            "",
            "Adds a temperature column to the per-core",
            "grid. Only visible when Read CPU Temperature",
            "succeeds.",
            "",
            "Default: on.",
        ],
        ConfigKey::ShowCpuFreq => &[
            "Show CPU frequency.",
            "",
            "Adds the current CPU clock speed (in GHz)",
            "next to the model name in the widget header.",
            "",
            "Default: on.",
        ],
        ConfigKey::ShowSwap => &[
            "Show swap (page file) usage.",
            "",
            "Adds page-file used and total to the memory",
            "widget. Hidden automatically when no page",
            "file exists.",
            "",
            "Default: on.",
        ],
        ConfigKey::ShowIoStat => &[
            "Inline read/write throughput row.",
            "",
            "Adds a small read+write number row beneath",
            "each disk in usage view. Has no effect in IO",
            "graph view.",
            "",
            "Default: on.",
        ],
        ConfigKey::IoMode => &[
            "IO graph view (current session).",
            "",
            "Replaces the per-disk usage meter with a",
            "read/write throughput graph. Reverts on",
            "restart unless Persistent IO Mode is on.",
            "",
            "Default: off.",
        ],
        ConfigKey::IoGraphCombined => &[
            "Combined read/write IO graph.",
            "",
            "Show one merged graph per disk instead of",
            "separate read and write graphs. Has effect",
            "only in IO graph view.",
            "",
            "Default: on.",
        ],
        ConfigKey::SwapUploadDownload => &[
            "Swap upload and download positions.",
            "",
            "By default download is on top and upload is",
            "on the bottom. Turn this on to swap them.",
            "",
            "Default: off.",
        ],
        ConfigKey::Base10Sizes => &[
            "Base-10 byte units.",
            "",
            "Show sizes as KB, MB, GB (1000-based)",
            "instead of KiB, MiB, GiB (1024-based).",
            "Applies to memory, disk, network, GPU, and",
            "process memory.",
            "",
            "Default: off.",
        ],
        ConfigKey::NetAuto => &[
            "Auto-scale network graph y-axis.",
            "",
            "Scales each graph to its largest visible",
            "value. Off uses the manual caps above.",
            "",
            "Default: on.",
        ],
        ConfigKey::NetSync => &[
            "Sync upload and download scales.",
            "",
            "Both graphs share the same y-axis maximum so",
            "their bar heights are directly comparable.",
            "",
            "Default: off.",
        ],
        ConfigKey::VimKeys => &[
            "Vim-style key bindings.",
            "",
            "Adds h/j/k/l for movement, g/G for top and",
            "bottom of lists, and Ctrl+F/B/D/U for paged",
            "scrolling. Arrow keys still work.",
            "",
            "Default: off.",
        ],
        ConfigKey::BackgroundUpdate => &[
            "Keep updating while menus are open.",
            "",
            "Off freezes the data behind a menu until you",
            "close it.",
            "",
            "Default: on.",
        ],
        ConfigKey::TerminalSync => &[
            "Synchronized terminal output.",
            "",
            "Reduces flicker on terminals that support",
            "the synchronized output sequence.",
            "",
            "Default: on.",
        ],
        ConfigKey::SaveConfigOnExit => &[
            "Write settings to disk on exit.",
            "",
            "Off keeps your changes to runtime settings",
            "only — they revert at the next launch.",
            "",
            "Default: on.",
        ],
        ConfigKey::DiskIoMode => &[
            "Persistent IO graph view.",
            "",
            "Same as IO Graph View, but persists across",
            "restarts.",
            "",
            "Default: off.",
        ],
        ConfigKey::UpdateMs => &[
            "Refresh interval (ms).",
            "",
            "How often widgets refresh by default. Each",
            "widget can override this with its own",
            "interval below.",
            "",
            "Default: 2,000 ms.",
            "Range: 100 to 86,400,000 ms.",
        ],
        ConfigKey::CpuUpdateMs => &[
            "CPU refresh interval (ms).",
            "",
            "Overrides the global Refresh Interval for",
            "the CPU widget. 0 inherits the global value.",
            "",
            "Default: 0 (inherit).",
            "Range: 0 to 86,400,000 ms.",
        ],
        ConfigKey::MemUpdateMs => &[
            "Memory refresh interval (ms).",
            "",
            "Overrides the global Refresh Interval for",
            "the memory widget. 0 inherits the global",
            "value.",
            "",
            "Default: 0 (inherit).",
            "Range: 0 to 86,400,000 ms.",
        ],
        ConfigKey::DiskUpdateMs => &[
            "Disk refresh interval (ms).",
            "",
            "Overrides the global Refresh Interval for",
            "the disk widget. 0 inherits the global",
            "value.",
            "",
            "Default: 0 (inherit).",
            "Range: 0 to 86,400,000 ms.",
        ],
        ConfigKey::NetUpdateMs => &[
            "Network refresh interval (ms).",
            "",
            "Overrides the global Refresh Interval for",
            "the network widget. 0 inherits the global",
            "value.",
            "",
            "Default: 0 (inherit).",
            "Range: 0 to 86,400,000 ms.",
        ],
        ConfigKey::GpuUpdateMs => &[
            "GPU refresh interval (ms).",
            "",
            "Overrides the global Refresh Interval for",
            "every GPU widget. 0 inherits the global",
            "value.",
            "",
            "Default: 0 (inherit).",
            "Range: 0 to 86,400,000 ms.",
        ],
        ConfigKey::ProcUpdateMs => &[
            "Process refresh interval (ms).",
            "",
            "Overrides the global Refresh Interval for",
            "the process list. 0 inherits the global",
            "value.",
            "",
            "Default: 0 (inherit).",
            "Range: 0 to 86,400,000 ms.",
        ],
        ConfigKey::NetDownload => &[
            "Manual download cap (KiB/s).",
            "",
            "Pins the download graph y-axis to this",
            "value. Has no effect when Auto Scale is on.",
            "Set to 0 to disable.",
            "",
            "Default: 100 KiB/s.",
            "Range: 0 to 10,000,000 KiB/s.",
        ],
        ConfigKey::NetUpload => &[
            "Manual upload cap (KiB/s).",
            "",
            "Pins the upload graph y-axis to this value.",
            "Has no effect when Auto Scale is on. Set to",
            "0 to disable.",
            "",
            "Default: 100 KiB/s.",
            "Range: 0 to 10,000,000 KiB/s.",
        ],
        ConfigKey::ColorTheme => &[
            "Color theme.",
            "",
            "Selects the color palette used throughout",
            "the interface. 41 themes ship with rtop.",
            "",
            "Default: default.",
        ],
        ConfigKey::ClockFormat => &[
            "Clock format (or empty to hide).",
            "",
            "Format for the clock shown in the CPU",
            "widget header.",
            "",
            "Supported tokens:",
            "  %X  full time (same as %H:%M:%S)",
            "  %H  hour (00-23)",
            "  %M  minute (00-59)",
            "  %S  second (00-59)",
            "",
            "Default: %X.",
        ],
        ConfigKey::CustomCpuName => &[
            "Custom CPU label (or empty for auto).",
            "",
            "Override the detected CPU model shown in the",
            "widget header. Empty uses the auto-detected",
            "name.",
            "",
            "Default: empty.",
        ],
        ConfigKey::ProcFilter => &[
            "Initial process filter.",
            "",
            "A starting filter string applied to the",
            "process list at launch. The 'f' or '/' key",
            "edits this at runtime.",
            "",
            "Default: empty.",
        ],
        ConfigKey::DisksFilter => &[
            "Disk include/exclude list.",
            "",
            "Whitespace-separated drive letters. Plain",
            "letters include only those drives; the !",
            "prefix excludes a drive. Empty shows all.",
            "",
            "Examples:",
            "  C:           show only C:",
            "  C: D:        show only C: and D:",
            "  !D:          show all except D:",
            "",
            "Default: empty.",
        ],
        ConfigKey::CustomLayout => &[
            "Layout for the custom preset.",
            "",
            "Build a layout by stacking widgets:",
            "",
            "  vstack(a, b, ...)",
            "    a above b above ...",
            "",
            "  hstack(W:a, W:b, ...)",
            "    a left of b left of ...",
            "    W = relative width (1-255)",
            "",
            "Widgets:",
            "  cpu mem net proc disk gpu0-gpu7",
            "",
            "Each widget may appear once.",
            "",
            "Example: cpu on top, mem and proc",
            "side-by-side underneath (60% proc):",
            "",
            "  vstack(cpu, hstack(40:mem, 60:proc))",
            "",
            "Cycle to the custom preset (p / P) to see",
            "your edits on screen.",
        ],
        ConfigKey::CustomGpuName0 => custom_gpu_desc(0),
        ConfigKey::CustomGpuName1 => custom_gpu_desc(1),
        ConfigKey::CustomGpuName2 => custom_gpu_desc(2),
        ConfigKey::CustomGpuName3 => custom_gpu_desc(3),
        ConfigKey::CustomGpuName4 => custom_gpu_desc(4),
        ConfigKey::CustomGpuName5 => custom_gpu_desc(5),
        ConfigKey::CustomGpuName6 => custom_gpu_desc(6),
        ConfigKey::CustomGpuName7 => custom_gpu_desc(7),
        ConfigKey::GraphSymbol => &[
            "Default graph style.",
            "",
            "The graph drawing style used by every widget",
            "that doesn't override it below. Braille is",
            "the highest resolution; ascii is the most",
            "compatible with limited terminals.",
            "",
            "Default: braille.",
        ],
        ConfigKey::GraphSymbolCpu => &[
            "CPU graph style override.",
            "",
            "Overrides the default graph style for the",
            "CPU widget. Use default to match Graph",
            "Symbol.",
            "",
            "Default: default.",
        ],
        ConfigKey::GraphSymbolNet => &[
            "Network graph style override.",
            "",
            "Overrides the default graph style for the",
            "network widget. Use default to match Graph",
            "Symbol.",
            "",
            "Default: default.",
        ],
        ConfigKey::GraphSymbolDisk => &[
            "Disk graph style override.",
            "",
            "Overrides the default graph style for the",
            "disk widget. Use default to match Graph",
            "Symbol.",
            "",
            "Default: default.",
        ],
        ConfigKey::ProcSorting => &[
            "Sort processes by.",
            "",
            "Which column the process list is sorted on.",
            "Press the left/right arrows on the process",
            "widget for the same effect at runtime.",
            "",
            "Default: cpu.",
        ],
        ConfigKey::CpuGraphUpper => &[
            "Upper CPU graph source.",
            "",
            "Which CPU statistic the larger top graph",
            "displays.",
            "",
            "Default: total.",
        ],
        ConfigKey::CpuGraphLower => &[
            "Lower CPU graph source.",
            "",
            "Which CPU statistic the smaller bottom graph",
            "displays. Has no effect when CPU Single",
            "Graph is on.",
            "",
            "Default: total.",
        ],
        ConfigKey::TempScale => &[
            "Temperature scale.",
            "",
            "Display temperatures in celsius or",
            "fahrenheit.",
            "",
            "Default: celsius.",
        ],
        ConfigKey::LogLevel => &[
            "Log verbosity.",
            "",
            "Off disables the log file. Higher levels",
            "capture more detail; warn or higher for",
            "normal use, info or debug when reporting a",
            "bug.",
            "",
            "Default: warn.",
        ],
    }
}

/// All eight `CustomGpuNameN` keys carry identical text up to the
/// device index. Centralising the template here keeps the
/// per-index entries above readable and avoids eight near-duplicate
/// arrays of strings.
fn custom_gpu_desc(index: u8) -> &'static [&'static str] {
    match index {
        0 => &[
            "Custom GPU 0 label (or empty for auto).",
            "",
            "Override the detected name for GPU 0. Empty",
            "keeps the auto-detected name from the vendor",
            "driver.",
            "",
            "Default: empty.",
        ],
        1 => &[
            "Custom GPU 1 label (or empty for auto).",
            "",
            "Override the detected name for GPU 1. Empty",
            "keeps the auto-detected name from the vendor",
            "driver.",
            "",
            "Default: empty.",
        ],
        2 => &[
            "Custom GPU 2 label (or empty for auto).",
            "",
            "Override the detected name for GPU 2. Empty",
            "keeps the auto-detected name from the vendor",
            "driver.",
            "",
            "Default: empty.",
        ],
        3 => &[
            "Custom GPU 3 label (or empty for auto).",
            "",
            "Override the detected name for GPU 3. Empty",
            "keeps the auto-detected name from the vendor",
            "driver.",
            "",
            "Default: empty.",
        ],
        4 => &[
            "Custom GPU 4 label (or empty for auto).",
            "",
            "Override the detected name for GPU 4. Empty",
            "keeps the auto-detected name from the vendor",
            "driver.",
            "",
            "Default: empty.",
        ],
        5 => &[
            "Custom GPU 5 label (or empty for auto).",
            "",
            "Override the detected name for GPU 5. Empty",
            "keeps the auto-detected name from the vendor",
            "driver.",
            "",
            "Default: empty.",
        ],
        6 => &[
            "Custom GPU 6 label (or empty for auto).",
            "",
            "Override the detected name for GPU 6. Empty",
            "keeps the auto-detected name from the vendor",
            "driver.",
            "",
            "Default: empty.",
        ],
        // 7 — last index in MAX_GPUS = 8 universe.
        _ => &[
            "Custom GPU 7 label (or empty for auto).",
            "",
            "Override the detected name for GPU 7. Empty",
            "keeps the auto-detected name from the vendor",
            "driver.",
            "",
            "Default: empty.",
        ],
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every variant of `ConfigKey` must have a non-empty desc
    /// entry — the menu otherwise renders an empty right-hand
    /// panel, which looks broken.
    ///
    /// We exercise this implicitly by walking the schema's
    /// `ConfigKey::parse` on every TOML name (the schema's
    /// inverse of `name()`); each produced key is passed through
    /// `desc()` and asserted non-empty. The macro guarantees the
    /// list of names matches the variant set, so this catches a
    /// future contributor who adds a config key without a
    /// matching desc entry.
    #[test]
    fn every_config_key_has_a_non_empty_desc() {
        // Iterate every known TOML name through ConfigKey::parse
        // (only available under #[cfg(test)]). For each parsed
        // key, desc() must return at least one line.
        for name in CANONICAL_NAMES {
            let key = ConfigKey::parse(name)
                .unwrap_or_else(|| panic!("unknown ConfigKey name in test fixture: {name}"));
            let lines = desc(key);
            assert!(!lines.is_empty(), "ConfigKey::{:?} has empty desc()", key,);
            assert!(
                !lines[0].is_empty(),
                "ConfigKey::{:?} has empty title line",
                key,
            );
        }
    }

    /// Hand-maintained list of canonical TOML names, kept in sync
    /// with the schema in `config.rs`. The
    /// `every_config_key_has_a_non_empty_desc` test loops this
    /// list — if a new key is added without updating both this
    /// fixture and `desc()`, the test fails.
    const CANONICAL_NAMES: &[&str] = &[
        "theme_background",
        "rounded_corners",
        "proc_reversed",
        "proc_tree",
        "proc_colors",
        "proc_gradient",
        "proc_per_core",
        "proc_mem_bytes",
        "proc_aggregate",
        "keep_dead_proc_usage",
        "cpu_invert_lower",
        "cpu_single_graph",
        "cpu_auto_scale",
        "show_uptime",
        "show_cpu_watts",
        "check_temp",
        "show_coretemp",
        "show_cpu_freq",
        "show_swap",
        "show_io_stat",
        "io_mode",
        "io_graph_combined",
        "swap_upload_download",
        "base_10_sizes",
        "net_auto",
        "net_sync",
        "vim_keys",
        "background_update",
        "terminal_sync",
        "save_config_on_exit",
        "disk_io_mode",
        "update_ms",
        "cpu_update_ms",
        "mem_update_ms",
        "disk_update_ms",
        "net_update_ms",
        "gpu_update_ms",
        "proc_update_ms",
        "net_download",
        "net_upload",
        "color_theme",
        "clock_format",
        "custom_cpu_name",
        "proc_filter",
        "disks_filter",
        "custom_layout",
        "custom_gpu_name0",
        "custom_gpu_name1",
        "custom_gpu_name2",
        "custom_gpu_name3",
        "custom_gpu_name4",
        "custom_gpu_name5",
        "custom_gpu_name6",
        "custom_gpu_name7",
        "graph_symbol",
        "graph_symbol_cpu",
        "graph_symbol_net",
        "graph_symbol_disk",
        "proc_sorting",
        "cpu_graph_upper",
        "cpu_graph_lower",
        "temp_scale",
        "log_level",
    ];
}
