//! Typed `ConfigKey` schema and per-key dispatch.
//!
//! Per-kind sub-enums (`BoolKey`, `IntKey`, `EnumKey`, `StringKey`)
//! own the variants for their kind. Each sub-enum exposes only the
//! operations that make sense for that kind — `BoolKey::toggle`,
//! `IntKey::set`, `EnumKey::set_canonical`, `StringKey::validate` —
//! so wrong-kind dispatch is *unrepresentable* in the type system
//! (no more "panic if called on the wrong kind" methods).
//!
//! `ConfigKey` is the user-facing wrapper that the options-menu
//! CAT lists carry. Callers pattern-match on it to recover the
//! typed inner key:
//!
//! ```text
//! match key {
//!     ConfigKey::Bool(k)   => k.toggle(config),
//!     ConfigKey::Int(k)    => /* enter int editor */,
//!     ConfigKey::Enum(k)   => /* cycle / commit canonical name */,
//!     ConfigKey::String(k) => /* enter string editor */,
//! }
//! ```
//!
//! `config_schema!` collapses the per-kind sub-enum generation +
//! the `ConfigKey` wrapper into one declarative table grouped by
//! kind. Each section enumerates its variants with the access shape
//! connecting each variant to its `Config` field.
//!
//! Access shapes (string-only — the other kinds are always
//! `field $f`):
//!
//! * `field $f` — direct `config.$f`
//! * `joined_vec $f` — `Vec<String>` displayed as a whitespace-joined string
//! * `array $f [$i]` — fixed-array element at index `$i`
//! * `custom_layout` — the layout DSL, virtual key whose display goes
//!   through `config.layout.custom_layout()` and write through
//!   `config.set_custom_layout()`
//!
//! Methods that carry per-variant logic (parse with bounds, validate
//! with per-key rules, set with per-shape destination) are
//! hand-written on the sub-enums after the macro expansion.

use crate::collect::process_display::ProcSort;
use crate::domain::config_enums::{CpuGraphSource, GraphSymbol, TempScale};
use crate::domain::layout_spec::Slot;

use super::{Config, KeyKind, SetStringError};

macro_rules! config_schema {
    (
        bools {
            $( $bvar:ident => $bname:literal => $bsection:ident . $bfield:ident ),* $(,)?
        }
        ints {
            $( $ivar:ident => $iname:literal => { $($ishape:tt)+ } ),* $(,)?
        }
        enums {
            $( $evar:ident => $ename:literal => $esection:ident . $efield:ident ),* $(,)?
        }
        strings {
            $( $svar:ident => $sname:literal => { $($sshape:tt)+ } ),* $(,)?
        }
    ) => {
        /// Boolean-typed config keys.
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        pub enum BoolKey { $( $bvar ),* }

        impl BoolKey {
            /// TOML field name (snake_case).
            pub fn name(self) -> &'static str {
                match self { $( Self::$bvar => $bname, )* }
            }

            /// Read the current bool value.
            pub fn get(self, config: &Config) -> bool {
                match self { $( Self::$bvar => config.$bsection.$bfield, )* }
            }

            /// Flip the bool in-place.
            pub fn toggle(self, config: &mut Config) {
                match self {
                    $( Self::$bvar => { config.$bsection.$bfield = !config.$bsection.$bfield; } )*
                }
            }

            /// Display string for the options menu (`"true"` / `"false"`).
            pub fn get_display(self, config: &Config) -> String {
                bool_display(self.get(config))
            }
        }

        /// Integer-typed config keys.
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        pub enum IntKey { $( $ivar ),* }

        impl IntKey {
            /// Every variant in declaration order. Generated by the
            /// `config_schema!` macro so adding a new int key
            /// automatically appears here.
            pub const ALL: &'static [IntKey] = &[ $( Self::$ivar ),* ];

            /// TOML field name (snake_case).
            pub fn name(self) -> &'static str {
                match self { $( Self::$ivar => $iname, )* }
            }

            /// Read the current int value.
            pub fn get(self, config: &Config) -> i64 {
                match self {
                    $( Self::$ivar => config_schema!(@int_get config $($ishape)+), )*
                }
            }

            /// Write the int value. No clamping — caller should
            /// invoke [`Config::validate`] to apply bounds.
            pub fn set(self, config: &mut Config, value: i64) {
                match self {
                    $( Self::$ivar => { config_schema!(@int_set config value $($ishape)+); } )*
                }
            }

            /// Display string for the options menu (the integer
            /// rendered in base 10).
            pub fn get_display(self, config: &Config) -> String {
                self.get(config).to_string()
            }
        }

        /// Typed-enum config keys (closed set of canonical names
        /// enforced by the underlying enum's `FromStr`).
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        pub enum EnumKey { $( $evar ),* }

        impl EnumKey {
            /// TOML field name (snake_case).
            pub fn name(self) -> &'static str {
                match self { $( Self::$evar => $ename, )* }
            }

            /// Display string for the options menu (the enum's
            /// canonical lowercase name via `Display`).
            pub fn get_display(self, config: &Config) -> String {
                match self { $( Self::$evar => config.$esection.$efield.to_string(), )* }
            }
        }

        /// String-typed config keys (free-form, constrained, list,
        /// or DSL).
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        pub enum StringKey { $( $svar ),* }

        impl StringKey {
            /// TOML field name (snake_case).
            pub fn name(self) -> &'static str {
                match self { $( Self::$svar => $sname, )* }
            }

            /// Display string for the options menu — the field
            /// value rendered for the access shape.
            pub fn get_display(self, config: &Config) -> String {
                match self {
                    $( Self::$svar => config_schema!(@string_display config $($sshape)+), )*
                }
            }
        }

        /// One config field, identified by its kind plus the typed
        /// sub-enum variant for that kind.
        ///
        /// The options-menu CAT lists carry `&[ConfigKey]`; callers
        /// pattern-match on the wrapper to recover the typed inner.
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        pub enum ConfigKey {
            Bool(BoolKey),
            Int(IntKey),
            Enum(EnumKey),
            String(StringKey),
        }

        impl ConfigKey {
            /// TOML field name (snake_case). Delegates to the
            /// typed inner.
            pub fn name(self) -> &'static str {
                match self {
                    Self::Bool(k) => k.name(),
                    Self::Int(k) => k.name(),
                    Self::Enum(k) => k.name(),
                    Self::String(k) => k.name(),
                }
            }

            /// Returns the kind of value this key holds.
            pub fn kind(self) -> KeyKind {
                match self {
                    Self::Bool(_) => KeyKind::Bool,
                    Self::Int(_) => KeyKind::Int,
                    Self::Enum(_) => KeyKind::Enum,
                    Self::String(_) => KeyKind::String,
                }
            }

            /// Returns a display string for the value of this key
            /// in the given config. Delegates to the typed inner.
            pub fn get_display(self, config: &Config) -> String {
                match self {
                    Self::Bool(k) => k.get_display(config),
                    Self::Int(k) => k.get_display(config),
                    Self::Enum(k) => k.get_display(config),
                    Self::String(k) => k.get_display(config),
                }
            }

            /// Parse a TOML field name into a `ConfigKey`.
            #[cfg(test)]
            pub fn parse(name: &str) -> Option<Self> {
                $( if name == $bname { return Some(Self::Bool(BoolKey::$bvar)); } )*
                $( if name == $iname { return Some(Self::Int(IntKey::$ivar)); } )*
                $( if name == $ename { return Some(Self::Enum(EnumKey::$evar)); } )*
                $( if name == $sname { return Some(Self::String(StringKey::$svar)); } )*
                None
            }
        }

        // `From` lets runtime callers lift typed keys to `ConfigKey`;
        // const CAT lists still spell out the wrapper variant.
        impl From<BoolKey>   for ConfigKey { fn from(k: BoolKey)   -> Self { Self::Bool(k) } }
        impl From<IntKey>    for ConfigKey { fn from(k: IntKey)    -> Self { Self::Int(k) } }
        impl From<EnumKey>   for ConfigKey { fn from(k: EnumKey)   -> Self { Self::Enum(k) } }
        impl From<StringKey> for ConfigKey { fn from(k: StringKey) -> Self { Self::String(k) } }
    };

    (@int_get $cfg:ident field $section:ident . $f:ident) => { $cfg.$section.$f };
    (@int_get $cfg:ident array $section:ident . $f:ident [$i:literal]) => { $cfg.$section.$f[$i] };
    (@int_set $cfg:ident $value:ident field $section:ident . $f:ident) => { $cfg.$section.$f = $value };
    (@int_set $cfg:ident $value:ident array $section:ident . $f:ident [$i:literal]) => { $cfg.$section.$f[$i] = $value };

    (@string_display $cfg:ident field $section:ident . $f:ident) => { $cfg.$section.$f.clone() };
    (@string_display $cfg:ident joined_vec $section:ident . $f:ident) => { $cfg.$section.$f.join(" ") };
    (@string_display $cfg:ident array $section:ident . $f:ident [$i:literal]) => { $cfg.$section.$f[$i].clone() };
    (@string_display $cfg:ident custom_layout) => { $cfg.layout.custom_layout().to_string() };
}

config_schema! {
    bools {
        ThemeBackground => "theme_background" => ui.theme_background,
        RoundedCorners => "rounded_corners" => ui.rounded_corners,
        ProcReversed => "proc_reversed" => view.proc_reversed,
        ProcTree => "proc_tree" => view.proc_tree,
        ProcColors => "proc_colors" => proc.proc_colors,
        ProcPerCore => "proc_per_core" => view.proc_per_core,
        ProcMemBytes => "proc_mem_bytes" => proc.proc_mem_bytes,
        ProcAggregate => "proc_aggregate" => proc.proc_aggregate,
        CpuInvertLower => "cpu_invert_lower" => cpu.cpu_invert_lower,
        CpuSingleGraph => "cpu_single_graph" => cpu.cpu_single_graph,
        CpuAutoScale => "cpu_auto_scale" => cpu.cpu_auto_scale,
        ShowCpuWatts => "show_cpu_watts" => cpu.show_cpu_watts,
        CheckTemp => "check_temp" => cpu.check_temp,
        ShowCoretemp => "show_coretemp" => cpu.show_coretemp,
        ShowCpuFreq => "show_cpu_freq" => cpu.show_cpu_freq,
        ShowSwap => "show_swap" => mem.show_swap,
        ShowIoStat => "show_io_stat" => disk.show_io_stat,
        IoMode => "io_mode" => view.io_mode,
        IoGraphCombined => "io_graph_combined" => disk.io_graph_combined,
        SwapUploadDownload => "swap_upload_download" => net.swap_upload_download,
        Base10Sizes => "base_10_sizes" => ui.base_10_sizes,
        NetAuto => "net_auto" => view.net_auto,
        NetSync => "net_sync" => view.net_sync,
        VimKeys => "vim_keys" => ui.vim_keys,
        BackgroundUpdate => "background_update" => ui.background_update,
        TerminalSync => "terminal_sync" => ui.terminal_sync,
        DiskIoMode => "disk_io_mode" => disk.disk_io_mode,
        ShowStatusbar => "show_statusbar" => statusbar.show_statusbar,
        StatusbarShowMenu => "statusbar_show_menu" => statusbar.statusbar_show_menu,
        StatusbarShowPreset => "statusbar_show_preset" => statusbar.statusbar_show_preset,
        StatusbarShowUpdateInterval => "statusbar_show_update_interval" => statusbar.statusbar_show_update_interval,
        StatusbarShowUptime => "statusbar_show_uptime" => statusbar.statusbar_show_uptime,
        StatusbarShowClock => "statusbar_show_clock" => statusbar.statusbar_show_clock,
    }
    ints {
        UpdateMs => "update_ms" => { field refresh.update_ms },
        CpuUpdateMs => "cpu_update_ms" => { field refresh.cpu_update_ms },
        MemUpdateMs => "mem_update_ms" => { field refresh.mem_update_ms },
        DiskUpdateMs => "disk_update_ms" => { field refresh.disk_update_ms },
        NetUpdateMs => "net_update_ms" => { field refresh.net_update_ms },
        GpuUpdateMs => "gpu_update_ms" => { field refresh.gpu_update_ms },
        ProcUpdateMs => "proc_update_ms" => { field refresh.proc_update_ms },
        NetDownload => "net_download" => { field net.net_download },
        NetUpload => "net_upload" => { field net.net_upload },
    }
    enums {
        GraphSymbol => "graph_symbol" => ui.graph_symbol,
        GraphSymbolCpu => "graph_symbol_cpu" => cpu.graph_symbol_cpu,
        GraphSymbolNet => "graph_symbol_net" => net.graph_symbol_net,
        GraphSymbolDisk => "graph_symbol_disk" => disk.graph_symbol_disk,
        ProcSorting => "proc_sorting" => view.proc_sorting,
        CpuGraphUpper => "cpu_graph_upper" => cpu.cpu_graph_upper,
        CpuGraphLower => "cpu_graph_lower" => cpu.cpu_graph_lower,
        TempScale => "temp_scale" => cpu.temp_scale,
        // `log_level` lives in `LogConfig` purely so the macro can
        // address it with the same `section.field` shape it uses
        // for every other key.
        LogLevel => "log_level" => log.log_level,
    }
    strings {
        ColorTheme => "color_theme" => { field ui.color_theme },
        StatusbarClockFormat => "statusbar_clock_format" => { field statusbar.statusbar_clock_format },
        CustomCpuName => "custom_cpu_name" => { field cpu.custom_cpu_name },
        ProcFilter => "proc_filter" => { field view.proc_filter },
        DiskFilter => "disk_filter" => { joined_vec disk.disk_filter },
        CustomLayout => "custom_layout" => { custom_layout },
    }
}

impl IntKey {
    /// Per-key step size used by the options-menu arrow-step path.
    /// `*UpdateMs` keys step in 100 ms increments; throughput caps
    /// step in single-unit increments.
    pub fn step(self) -> i64 {
        match self {
            Self::UpdateMs
            | Self::CpuUpdateMs
            | Self::MemUpdateMs
            | Self::DiskUpdateMs
            | Self::NetUpdateMs
            | Self::GpuUpdateMs
            | Self::ProcUpdateMs => 100,
            Self::NetDownload | Self::NetUpload => 1,
        }
    }

    /// Inclusive `[min, max]` bounds for this key. The single source
    /// of truth — both [`Self::parse`] (rejecting out-of-range input
    /// from the inline editor) and [`Self::clamp_to_bounds`]
    /// (clamping out-of-range values from a loaded TOML file)
    /// consult this method.
    pub fn bounds(self) -> std::ops::RangeInclusive<i64> {
        match self {
            Self::UpdateMs => 100..=86_400_000,
            Self::CpuUpdateMs
            | Self::MemUpdateMs
            | Self::DiskUpdateMs
            | Self::NetUpdateMs
            | Self::GpuUpdateMs
            | Self::ProcUpdateMs => 0..=86_400_000,
            Self::NetDownload | Self::NetUpload => 0..=10_000_000,
        }
    }

    /// Parse `value` as an integer for this key, enforcing the bounds
    /// returned by [`Self::bounds`].
    pub fn parse(self, value: &str) -> Result<i64, &'static str> {
        let trimmed = value.trim();
        if trimmed.is_empty() {
            return Err("must be an integer");
        }
        let n: i64 = trimmed.parse().map_err(|_| "must be an integer")?;
        if self.bounds().contains(&n) {
            Ok(n)
        } else {
            Err(self.bounds_message())
        }
    }

    /// Clamp `value` into [`Self::bounds`], returning the in-range
    /// value. Used by [`Config::validate`] after loading a TOML file
    /// so out-of-range values land at the nearest valid edge instead
    /// of failing the whole load.
    pub fn clamp_to_bounds(self, value: i64) -> i64 {
        let bounds = self.bounds();
        value.clamp(*bounds.start(), *bounds.end())
    }

    /// Static error message naming the legal range for this key.
    pub fn bounds_message(self) -> &'static str {
        match self {
            Self::UpdateMs => "must be 100..86400000 ms",
            Self::CpuUpdateMs
            | Self::MemUpdateMs
            | Self::DiskUpdateMs
            | Self::NetUpdateMs
            | Self::GpuUpdateMs
            | Self::ProcUpdateMs => "must be 0..86400000 ms (0=inherit)",
            Self::NetDownload | Self::NetUpload => "must be 0..10000000 KiB/s",
        }
    }
}

impl EnumKey {
    /// The closed set of canonical (lowercase) names the menu
    /// cycles for this enum key.
    pub fn choices(self) -> &'static [&'static str] {
        match self {
            Self::GraphSymbol
            | Self::GraphSymbolCpu
            | Self::GraphSymbolNet
            | Self::GraphSymbolDisk => GraphSymbol::NAMES,
            Self::CpuGraphUpper | Self::CpuGraphLower => CpuGraphSource::NAMES,
            Self::TempScale => TempScale::NAMES,
            Self::ProcSorting => ProcSort::NAMES,
            Self::LogLevel => crate::log::FILTER_NAMES,
        }
    }

    /// Parse a canonical name into the typed enum and store it in
    /// `config`. Returns `Err(SetStringError)` if `value` is not in
    /// [`Self::choices`].
    pub fn set_canonical(self, config: &mut Config, value: &str) -> Result<(), SetStringError> {
        let err = || SetStringError {
            key: self.name(),
            value: value.to_string(),
        };
        match self {
            Self::GraphSymbol => config.ui.graph_symbol = value.parse().map_err(|_| err())?,
            Self::GraphSymbolCpu => {
                config.cpu.graph_symbol_cpu = value.parse().map_err(|_| err())?
            }
            Self::GraphSymbolNet => {
                config.net.graph_symbol_net = value.parse().map_err(|_| err())?
            }
            Self::GraphSymbolDisk => {
                config.disk.graph_symbol_disk = value.parse().map_err(|_| err())?
            }
            Self::ProcSorting => config.view.proc_sorting = value.parse().map_err(|_| err())?,
            Self::CpuGraphUpper => config.cpu.cpu_graph_upper = value.parse().map_err(|_| err())?,
            Self::CpuGraphLower => config.cpu.cpu_graph_lower = value.parse().map_err(|_| err())?,
            Self::TempScale => config.cpu.temp_scale = value.parse().map_err(|_| err())?,
            Self::LogLevel => config.log.log_level = value.parse().map_err(|_| err())?,
        }
        Ok(())
    }
}

impl StringKey {
    /// Optional closed set of canonical names. `Some` only for
    /// constrained string keys (today: just `color_theme`); `None`
    /// for free-form keys and the special `disk_filter` /
    /// `custom_layout` parsers.
    pub fn choices(self) -> Option<&'static [&'static str]> {
        match self {
            Self::ColorTheme => Some(crate::theme::THEME_NAMES),
            _ => None,
        }
    }

    /// Validate that `value` is acceptable without mutating the
    /// config. Returns a static error message suitable for inline
    /// display in the options menu when validation fails.
    ///
    /// Used by the inline editor commit path: validate first, only
    /// call [`Self::set`] when validation succeeds.
    pub fn validate(self, value: &str) -> Result<(), &'static str> {
        match self {
            Self::CustomLayout => value
                .parse::<Slot>()
                .map(|_| ())
                .map_err(|_| "invalid layout"),
            Self::DiskFilter => parse_disk_filter(value).map(|_| ()),
            Self::ColorTheme => {
                if self
                    .choices()
                    .expect("ColorTheme has choices by construction")
                    .contains(&value)
                {
                    Ok(())
                } else {
                    Err("invalid value")
                }
            }
            // Free-form string keys accept anything.
            Self::StatusbarClockFormat | Self::CustomCpuName | Self::ProcFilter => Ok(()),
        }
    }

    /// Set the field from a string. Returns `Err(SetStringError)`
    /// if `value` does not parse for the field's shape (currently
    /// only `CustomLayout` and `DiskFilter` can fail here; other
    /// string keys are free-form or pre-validated by the caller).
    pub fn set(self, config: &mut Config, value: &str) -> Result<(), SetStringError> {
        let err = || SetStringError {
            key: self.name(),
            value: value.to_string(),
        };
        match self {
            Self::ColorTheme => config.ui.color_theme = value.to_string(),
            Self::StatusbarClockFormat => {
                config.statusbar.statusbar_clock_format = value.to_string()
            }
            Self::CustomCpuName => config.cpu.custom_cpu_name = value.to_string(),
            Self::ProcFilter => config.view.proc_filter = value.to_string(),
            Self::CustomLayout => {
                config.set_custom_layout(value).map_err(|_| err())?;
            }
            Self::DiskFilter => {
                config.disk.disk_filter = parse_disk_filter(value).map_err(|_| err())?;
            }
        }
        Ok(())
    }
}

/// Parse `value` as a whitespace-separated list of drive filter
/// entries (e.g. `"C: !D:"`).
///
/// An empty list is allowed (matches every disk). Each entry must
/// be a single ASCII letter followed by `:`, optionally prefixed
/// with `!`. Returns the original token list (so case and `!`
/// prefixes are preserved verbatim for round-trip fidelity);
/// normalisation happens at match time.
pub(super) fn parse_disk_filter(value: &str) -> Result<Vec<String>, &'static str> {
    let tokens: Vec<String> = value.split_whitespace().map(str::to_string).collect();
    let parsed = crate::domain::disk::DiskFilter::parse(&tokens);
    if !parsed.invalid().is_empty() {
        return Err("drive entries must be like 'C:' or '!D:'");
    }
    Ok(tokens)
}

fn bool_display(v: bool) -> String {
    if v {
        "true".to_string()
    } else {
        "false".to_string()
    }
}
