[colors]
main_bg = "#0B0E14"
main_fg = "#BFBDB6"
data_label_fg = "#80807d"
title = "#BFBDB6"
hi_fg = "#E6B450"
graph_text = "#BFBDB6"
meter_bg = "#565B66"
selected_bg = "#E6B450"
selected_fg = "#f8f8f2"
followed_bg = "#F28779"
followed_fg = "#f8f8f2"
inactive_fg = "#656665"
cpu_widget = "#DFBFFF"
mem_widget = "#95E6CB"
net_widget = "#F28779"
proc_widget = "#E6B673"
gpu_widget = "#73C2E6"
disk_widget = "#E6A0CB"
help_box = "#73B8E6"
options_box = "#E6B873"
proc_tree_fg = "#565B66"

statusbar_bg = "#0B0E14"
statusbar_fg = "#BFBDB6"
statusbar_hi = "#E6B450"
statusbar_sep = "#656665"

[gradients.cpu_upper]
start = "#DFBFFF"
mid = "#D2A6FF"
end = "#A37ACC"

[gradients.cpu_lower]
start = "#73D0FF"
mid = "#59C2FF"
end = "#399EE6"

[gradients.used]
start = "#95E6CB"
mid = "#95E6CB"
end = "#4CBF99"

[gradients.available]
start = "#95E6CB"
mid = "#95E6CB"
end = "#4CBF99"

[gradients.cached]
start = "#95E6CB"
mid = "#95E6CB"
end = "#4CBF99"

[gradients.free]
start = "#95E6CB"
mid = "#95E6CB"
end = "#4CBF99"

[gradients.download]
start = "#F28779"
mid = "#F07178"
end = "#F07171"

[gradients.upload]
start = "#73D0FF"
mid = "#59C2FF"
end = "#399EE6"

[gradients.gpu]
start = "#DFBFFF"
mid = "#D2A6FF"
end = "#A37ACC"

[gradients.gpu_clock]
start = "#73C2E6"
mid = "#59B0D4"
end = "#3F9EC2"

[gradients.gpu_power]
start = "#FFB454"
mid = "#F29718"
end = "#E6730D"

[gradients.gpu_vram]
start = "#BAE67A"
mid = "#A8D54E"
end = "#8CC730"

[gradients.disk_read]
start = "#F28779"
mid = "#F07178"
end = "#F07171"

[gradients.disk_write]
start = "#73D0FF"
mid = "#59C2FF"
end = "#399EE6"

[gradients.disk_busy]
start = "#95E6CB"
mid = "#95E6CB"
end = "#4CBF99"

[gradients.temp]
start = "#DFBFFF"
mid = "#D2A6FF"
end = "#A37ACC"

[gradients.process]
start = "#FFCC66"
mid = "#E6B450"
end = "#FFAA33"


