[colors]
main_bg = "#282a36"
main_fg = "#f8f8f2"
title = "#f8f8f2"
hi_fg = "#6272a4"
selected_bg = "#ff79c6"
selected_fg = "#f8f8f2"
inactive_fg = "#44475a"
graph_text = "#f8f8f2"
meter_bg = "#44475a"
proc_misc = "#bd93f9"
proc_tree_fg = "#44475a"
cpu_box = "#bd93f9"
mem_box = "#50fa7b"
net_box = "#ff5555"
proc_box = "#8be9fd"
gpu_box = "#f1fa8c"
disk_box = "#ffb86c"
help_box = "#6272a4"
options_box = "#ffb86c"
div_line = "#44475a"
proc_pause_bg = "#0dfa49"
proc_follow_bg = "#bd93f9"
proc_banner_bg = "#ff79c6"
proc_banner_fg = "#f8f8f2"
followed_bg = "#bd93f9"
followed_fg = "#f8f8f2"

[gradients.temp]
start = "#bd93f9"
mid = "#ff79c6"
end = "#ff33a8"

[gradients.cpu]
start = "#bd93f9"
mid = "#8be9fd"
end = "#50fa7b"

[gradients.free]
start = "#ffa6d9"
mid = "#ff79c6"
end = "#ff33a8"

[gradients.cached]
start = "#b1f0fd"
mid = "#8be9fd"
end = "#26d7fd"

[gradients.available]
start = "#ffd4a6"
mid = "#ffb86c"
end = "#ff9c33"

[gradients.used]
start = "#96faaf"
mid = "#50fa7b"
end = "#0dfa49"

[gradients.download]
start = "#bd93f9"
mid = "#50fa7b"
end = "#8be9fd"

[gradients.upload]
start = "#8c42ab"
mid = "#ff79c6"
end = "#ff33a8"

[gradients.disk_read]
start = "#bd93f9"
mid = "#50fa7b"
end = "#8be9fd"

[gradients.disk_write]
start = "#8c42ab"
mid = "#ff79c6"
end = "#ff33a8"

[gradients.disk_busy]
start = "#96faaf"
mid = "#50fa7b"
end = "#0dfa49"

[gradients.process]
start = "#50fa7b"
mid = "#59b690"
end = "#6272a4"

[gradients.gpu]
start = "#bd93f9"
mid = "#8be9fd"
end = "#50fa7b"

[gradients.gpu_clock]
start = "#8be9fd"
mid = "#6272a4"
end = "#44475a"

[gradients.gpu_power]
start = "#ffb86c"
mid = "#ff79c6"
end = "#ff5555"

[gradients.gpu_vram]
start = "#bd93f9"
mid = "#ff79c6"
end = "#f1fa8c"

