[colors]
main_bg = "#04142E"
main_fg = "#99DFFF"
title = "#99FFFF"
hi_fg = "#FF7F00"
selected_bg = "#722B01"
selected_fg = "#99FFFF"
inactive_fg = "#052E51"
graph_text = "#79A1B4"
meter_bg = "#052E51"
proc_misc = "#B46718"
proc_tree_fg = "#052E51"
cpu_box = "#00FFFF"
mem_box = "#00FFFF"
net_box = "#00FFFF"
proc_box = "#00FFFF"
gpu_box = "#00FFFF"
disk_box = "#00FFFF"
help_box = "#00FFFF"
options_box = "#00FFFF"
div_line = "#A55800"
proc_pause_bg = "#B46718"
proc_follow_bg = "#009EFF"
proc_banner_bg = "#722B01"
proc_banner_fg = "#99FFFF"
followed_bg = "#009EFF"
followed_fg = "#99FFFF"

[gradients.temp]
start = "#00ADFF"
mid = "#00FFFF"
end = "#FFF86B"

[gradients.cpu]
start = "#00D4FF"
mid = "#FFF86B"
end = "#FF7F00"

[gradients.free]
start = "#0187CB"
mid = "#0187cb"
end = "#0187CB"

[gradients.cached]
start = "#B4BB63"
mid = "#b4bb63"
end = "#B4BB63"

[gradients.available]
start = "#01C0CB"
mid = "#01c0cb"
end = "#01C0CB"

[gradients.used]
start = "#B46718"
mid = "#b46718"
end = "#B46718"

[gradients.download]
start = "#009EFF"
mid = "#00ceff"
end = "#00FFFF"

[gradients.upload]
start = "#FF7F00"
mid = "#ffbb35"
end = "#FFF86B"

[gradients.disk_read]
start = "#009EFF"
mid = "#00ceff"
end = "#00FFFF"

[gradients.disk_write]
start = "#FF7F00"
mid = "#ffbb35"
end = "#FFF86B"

[gradients.disk_busy]
start = "#B46718"
mid = "#b46718"
end = "#B46718"

[gradients.process]
start = "#00D4FF"
mid = "#FFF86B"
end = "#FF7F00"

[gradients.gpu]
start = "#00D4FF"
mid = "#FFF86B"
end = "#FF7F00"

[gradients.gpu_clock]
start = "#00ADFF"
mid = "#00FFFF"
end = "#80FFFF"

[gradients.gpu_power]
start = "#FF7F00"
mid = "#FF5722"
end = "#FF1744"

[gradients.gpu_vram]
start = "#B388FF"
mid = "#7C4DFF"
end = "#651FFF"

