[colors]
main_bg = "#04142E"
main_fg = "#99DFFF"
title = "#99FFFF"
hi_fg = "#FF7F00"
graph_text = "#79A1B4"
meter_bg = "#052E51"
selected_bg = "#722B01"
selected_fg = "#99FFFF"
followed_bg = "#009EFF"
followed_fg = "#99FFFF"
dead_proc_fg = "#4e7a96"
cpu_widget = "#00FFFF"
mem_widget = "#00FFFF"
net_widget = "#00FFFF"
proc_widget = "#00FFFF"
gpu_widget = "#00FFFF"
disk_widget = "#00FFFF"
help_box = "#00FFFF"
options_box = "#00FFFF"
proc_tree_fg = "#052E51"

statusbar_bg = "#04142E"
statusbar_fg = "#99FFFF"
statusbar_hi = "#FF7F00"
statusbar_sep = "#79A1B4"

menu_fg = "#99dfff"
menu_hi_fg = "#ff7f00"
[gradients.cpu_upper]
start = "#00D4FF"
mid = "#FFF86B"
end = "#FF7F00"

[gradients.cpu_lower]
start = "#009EFF"
mid = "#5C5BBF"
end = "#B96BFF"

[gradients.used]
start = "#B46718"
mid = "#b46718"
end = "#B46718"

[gradients.available]
start = "#01C0CB"
mid = "#01c0cb"
end = "#01C0CB"

[gradients.cached]
start = "#B4BB63"
mid = "#b4bb63"
end = "#B4BB63"

[gradients.free]
start = "#0187CB"
mid = "#0187cb"
end = "#0187CB"

[gradients.download]
start = "#009EFF"
mid = "#00ceff"
end = "#00FFFF"

[gradients.upload]
start = "#FF7F00"
mid = "#ffbb35"
end = "#FFF86B"

[gradients.gpu]
start = "#00D4FF"
mid = "#FFF86B"
end = "#FF7F00"

[gradients.gpu_clock]
start = "#00ADFF"
mid = "#00FFFF"
end = "#80FFFF"

[gradients.gpu_power]
start = "#FF7F00"
mid = "#FF5722"
end = "#FF1744"

[gradients.gpu_vram]
start = "#B388FF"
mid = "#7C4DFF"
end = "#651FFF"

[gradients.disk_read]
start = "#009EFF"
mid = "#00ceff"
end = "#00FFFF"

[gradients.disk_write]
start = "#FF7F00"
mid = "#ffbb35"
end = "#FFF86B"

[gradients.disk_busy]
start = "#B46718"
mid = "#b46718"
end = "#B46718"

[gradients.temp]
start = "#00ADFF"
mid = "#00FFFF"
end = "#FFF86B"

[gradients.process]
start = "#00D4FF"
mid = "#FFF86B"
end = "#FF7F00"


