# Theme: Elementarish
# (inspired by Elementary OS)
# By: Dennis Mayr

# Main bg
theme[main_bg]="#333333"

# Main text color
theme[main_fg]="#eee8d5"

# Title color for boxes
theme[title]="#eee8d5"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#d1302c"

# Background color of selected item in processes box
theme[selected_bg]="#268ad0"

# Foreground color of selected item in processes box
theme[selected_fg]="#eee8d5"

# Color of inactive/disabled text
theme[inactive_fg]="#657b83"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#268ad0"

# Cpu box outline color
theme[cpu_box]="#657b83"

# Memory/disks box outline color
theme[mem_box]="#657b83"

# Net up/down box outline color
theme[net_box]="#657b83"

# Processes box outline color
theme[proc_box]="#657b83"

# Gpu box outline color
theme[gpu_box]="#657b83"

# Disk box outline color
theme[disk_box]="#657b83"

# Help menu box outline color
theme[help_box]="#657b83"

# Options menu box outline color
theme[options_box]="#657b83"

# Box divider line and small boxes line color
theme[div_line]="#657b83"

# Temperature graph colors
theme[temp_start]="#859900"
theme[temp_mid]="#b28602"
theme[temp_end]="#d1302c"

# CPU graph colors
theme[cpu_start]="#859900"
theme[cpu_mid]="#b28602"
theme[cpu_end]="#d1302c"

# Mem/Disk free meter
theme[free_start]="#268ad0"
theme[free_mid]="#6c71c4"
theme[free_end]="#2a9d95"

# Mem/Disk cached meter
theme[cached_start]="#268ad0"
theme[cached_mid]="#6c71c4"
theme[cached_end]="#d1302c"

# Mem/Disk available meter
theme[available_start]="#268ad0"
theme[available_mid]="#6c71c4"
theme[available_end]="#d1302c"

# Mem/Disk used meter
theme[used_start]="#859900"
theme[used_mid]="#b28602"
theme[used_end]="#d1302c"

# Download graph colors
theme[download_start]="#268ad0"
theme[download_mid]="#6c71c4"
theme[download_end]="#d1302c"

# Upload graph colors
theme[upload_start]="#268ad0"
theme[upload_mid]="#6c71c4"
theme[upload_end]="#d1302c"

# GPU utilization meter
theme[gpu_start]="#859900"
theme[gpu_mid]="#b28602"
theme[gpu_end]="#d1302c"

# GPU clock speed meter
theme[gpu_clock_start]="#2a9d95"
theme[gpu_clock_mid]="#268ad0"
theme[gpu_clock_end]="#6c71c4"

# GPU power draw meter
theme[gpu_power_start]="#cb4b16"
theme[gpu_power_mid]="#b28602"
theme[gpu_power_end]="#d1302c"

# GPU VRAM usage meter
theme[gpu_vram_start]="#6c71c4"
theme[gpu_vram_mid]="#8066b0"
theme[gpu_vram_end]="#d33682"
