[colors]
main_bg = "#2d353b"
main_fg = "#d3c6aa"
title = "#d3c6aa"
hi_fg = "#e67e80"
graph_text = "#d3c6aa"
meter_bg = "#2d353b"
selected_bg = "#3d484d"
selected_fg = "#dbbc7f"
followed_bg = "#a7c080"
followed_fg = "#dbbc7f"
cpu_box = "#3d484d"
mem_box = "#3d484d"
net_box = "#3d484d"
proc_box = "#3d484d"
gpu_box = "#3d484d"
disk_box = "#3d484d"
help_box = "#3d484d"
options_box = "#3d484d"
proc_tree_fg = "#2d353b"

[gradients.cpu_upper]
start = "#a7c080"
mid = "#dbbc7f"
end = "#f85552"

[gradients.cpu_lower]
start = "#4897d4"
mid = "#5474e8"
end = "#ff40b6"

[gradients.used]
start = "#a7c080"
mid = "#dbbc7f"
end = "#f85552"

[gradients.available]
start = "#f85552"
mid = "#dbbc7f"
end = "#a7c080"

[gradients.cached]
start = "#7fbbb3"
mid = "#83c092"
end = "#a7c080"

[gradients.free]
start = "#f85552"
mid = "#dbbc7f"
end = "#a7c080"

[gradients.download]
start = "#a7c080"
mid = "#83c092"
end = "#7fbbb3"

[gradients.upload]
start = "#dbbc7f"
mid = "#e69875"
end = "#e67e80"

[gradients.gpu]
start = "#a7c080"
mid = "#dbbc7f"
end = "#f85552"

[gradients.gpu_clock]
start = "#7fbbb3"
mid = "#83c092"
end = "#a7c080"

[gradients.gpu_power]
start = "#e69875"
mid = "#dbbc7f"
end = "#f85552"

[gradients.gpu_vram]
start = "#d699b6"
mid = "#d3869b"
end = "#b57286"

[gradients.disk_read]
start = "#a7c080"
mid = "#83c092"
end = "#7fbbb3"

[gradients.disk_write]
start = "#dbbc7f"
mid = "#e69875"
end = "#e67e80"

[gradients.disk_busy]
start = "#a7c080"
mid = "#dbbc7f"
end = "#f85552"

[gradients.temp]
start = "#a7c080"
mid = "#dbbc7f"
end = "#f85552"

[gradients.process]
start = "#a7c080"
mid = "#e67e80"
end = "#f85552"


