[colors]
main_bg = "#fdf6e3"
main_fg = "#5c6a72"
title = "#5c6a72"
hi_fg = "#df69ba"
graph_text = "#5c6a72"
meter_bg = "#9DA9A0"
selected_bg = "#4F585E"
selected_fg = "#dfa000"
followed_bg = "#8da101"
followed_fg = "#dfa000"
dead_proc_fg = "#acb0aa"
cpu_widget = "#4F585E"
mem_widget = "#4F585E"
net_widget = "#4F585E"
proc_widget = "#4F585E"
gpu_widget = "#4F585E"
disk_widget = "#4F585E"
help_box = "#4F585E"
options_box = "#4F585E"
proc_tree_fg = "#9DA9A0"

[gradients.cpu_upper]
start = "#8da101"
mid = "#dfa000"
end = "#f85552"

[gradients.cpu_lower]
start = "#3994c5"
mid = "#a85b8b"
end = "#df69ba"

[gradients.used]
start = "#8da101"
mid = "#dfa000"
end = "#f85552"

[gradients.available]
start = "#f85552"
mid = "#dfa000"
end = "#8da101"

[gradients.cached]
start = "#3994c5"
mid = "#35a77c"
end = "#8da101"

[gradients.free]
start = "#f85552"
mid = "#dfa000"
end = "#8da101"

[gradients.download]
start = "#8da101"
mid = "#35a77c"
end = "#3994c5"

[gradients.upload]
start = "#dfa000"
mid = "#e66868"
end = "#df69ba"

[gradients.gpu]
start = "#8da101"
mid = "#dfa000"
end = "#f85552"

[gradients.gpu_clock]
start = "#3994c5"
mid = "#35a77c"
end = "#8da101"

[gradients.gpu_power]
start = "#e67e50"
mid = "#dfa000"
end = "#f85552"

[gradients.gpu_vram]
start = "#b57286"
mid = "#d3869b"
end = "#d699b6"

[gradients.disk_read]
start = "#8da101"
mid = "#35a77c"
end = "#3994c5"

[gradients.disk_write]
start = "#dfa000"
mid = "#e66868"
end = "#df69ba"

[gradients.disk_busy]
start = "#8da101"
mid = "#dfa000"
end = "#f85552"

[gradients.temp]
start = "#8da101"
mid = "#dfa000"
end = "#f85552"

[gradients.process]
start = "#8da101"
mid = "#df69ba"
end = "#f85552"


