[colors]
main_bg = "#faf4e8"
main_fg = "#1f1a12"
data_label_fg = "#6c665d"
title = "#1f1a12"
hi_fg = "#895600"
graph_text = "#b0a48e"
meter_bg = "#ddd5c2"
selected_bg = "#eadcc4"
selected_fg = "#1f1a12"
followed_bg = "#d2ccb7"
followed_fg = "#1f1a12"
inactive_fg = "#746a5a"
cpu_widget = "#932100"
mem_widget = "#896d00"
net_widget = "#1e5d9c"
proc_widget = "#007c48"
gpu_widget = "#007379"
disk_widget = "#93427c"
help_box = "#007379"
options_box = "#896d00"
proc_tree_fg = "#b0a48e"

statusbar_bg = "#faf4e8"
statusbar_fg = "#1f1a12"
statusbar_hi = "#895600"
statusbar_sep = "#726554"

[gradients.cpu_upper]
start = "#007c48"
mid = "#896d00"
end = "#932100"

[gradients.cpu_lower]
start = "#1e5d9c"
mid = "#893d00"
end = "#932100"

[gradients.used]
start = "#896d00"
mid = "#893d00"
end = "#932100"

[gradients.available]
start = "#6a5e50"
mid = "#007c48"
end = "#006633"

[gradients.cached]
start = "#1e5d9c"
mid = "#007379"
end = "#005d63"

[gradients.free]
start = "#4b6057"
mid = "#007c48"
end = "#006633"

[gradients.download]
start = "#1e5d9c"
mid = "#007379"
end = "#004784"

[gradients.upload]
start = "#93427c"
mid = "#893d00"
end = "#7b2c66"

[gradients.gpu]
start = "#007c48"
mid = "#896d00"
end = "#932100"

[gradients.gpu_clock]
start = "#1e5d9c"
mid = "#007379"
end = "#005d63"

[gradients.gpu_power]
start = "#896d00"
mid = "#893d00"
end = "#932100"

[gradients.gpu_vram]
start = "#93427c"
mid = "#893d00"
end = "#7b2c66"

[gradients.disk_read]
start = "#1e5d9c"
mid = "#007379"
end = "#004784"

[gradients.disk_write]
start = "#93427c"
mid = "#893d00"
end = "#7b2c66"

[gradients.disk_busy]
start = "#896d00"
mid = "#893d00"
end = "#932100"

[gradients.temp]
start = "#1e5d9c"
mid = "#893d00"
end = "#932100"

[gradients.process]
start = "#007c48"
mid = "#896d00"
end = "#932100"
