[colors]
main_bg = "#0e0c0a"
main_fg = "#d0c8b8"
data_label_fg = "#8c867b"
title = "#e8e0d0"
hi_fg = "#c48e3f"
graph_text = "#484040"
meter_bg = "#1a2824"
selected_bg = "#3c2a1e"
selected_fg = "#d0c8b8"
followed_bg = "#1e3830"
followed_fg = "#d0c8b8"
inactive_fg = "#82796f"
cpu_widget = "#cf5a3b"
mem_widget = "#c7ab35"
net_widget = "#5290d3"
proc_widget = "#50b27a"
gpu_widget = "#2ea3a9"
disk_widget = "#c16ca6"
help_box = "#2ea3a9"
options_box = "#c7ab35"
proc_tree_fg = "#484040"

statusbar_bg = "#0e0c0a"
statusbar_fg = "#d0c8b8"
statusbar_hi = "#c48e3f"
statusbar_sep = "#8a8073"

[gradients.cpu_upper]
start = "#50b27a"
mid = "#c7ab35"
end = "#cf5a3b"

[gradients.cpu_lower]
start = "#5290d3"
mid = "#bb6a26"
end = "#cf5a3b"

[gradients.used]
start = "#c7ab35"
mid = "#bb6a26"
end = "#cf5a3b"

[gradients.available]
start = "#948576"
mid = "#50b27a"
end = "#66c78e"

[gradients.cached]
start = "#5290d3"
mid = "#2ea3a9"
end = "#48b8be"

[gradients.free]
start = "#73897f"
mid = "#50b27a"
end = "#66c78e"

[gradients.download]
start = "#5290d3"
mid = "#2ea3a9"
end = "#66a4e9"

[gradients.upload]
start = "#c16ca6"
mid = "#bb6a26"
end = "#d780bb"

[gradients.gpu]
start = "#50b27a"
mid = "#c7ab35"
end = "#cf5a3b"

[gradients.gpu_clock]
start = "#5290d3"
mid = "#2ea3a9"
end = "#48b8be"

[gradients.gpu_power]
start = "#c7ab35"
mid = "#bb6a26"
end = "#cf5a3b"

[gradients.gpu_vram]
start = "#c16ca6"
mid = "#bb6a26"
end = "#d780bb"

[gradients.disk_read]
start = "#5290d3"
mid = "#2ea3a9"
end = "#66a4e9"

[gradients.disk_write]
start = "#c16ca6"
mid = "#bb6a26"
end = "#d780bb"

[gradients.disk_busy]
start = "#c7ab35"
mid = "#bb6a26"
end = "#cf5a3b"

[gradients.temp]
start = "#5290d3"
mid = "#bb6a26"
end = "#cf5a3b"

[gradients.process]
start = "#50b27a"
mid = "#c7ab35"
end = "#cf5a3b"
