[colors]
main_bg = "#f4ecdc"
main_fg = "#1f1a12"
title = "#1f1a12"
hi_fg = "#8d5500"
graph_text = "#b0a48e"
meter_bg = "#d8cdb4"
selected_bg = "#e6d4b4"
selected_fg = "#1f1a12"
followed_bg = "#cdc4a8"
followed_fg = "#1f1a12"
dead_proc_fg = "#746a5a"
cpu_widget = "#a53912"
mem_widget = "#765c00"
net_widget = "#2d568c"
proc_widget = "#006b3c"
gpu_widget = "#006570"
disk_widget = "#89436e"
help_box = "#006570"
options_box = "#765c00"
proc_tree_fg = "#b0a48e"

statusbar_bg = "#f4ecdc"
statusbar_fg = "#1f1a12"
statusbar_hi = "#8d5500"
statusbar_sep = "#726554"

[gradients.cpu_upper]
start = "#006b3c"
mid = "#765c00"
end = "#a53912"

[gradients.cpu_lower]
start = "#2d568c"
mid = "#8a4517"
end = "#a53912"

[gradients.used]
start = "#765c00"
mid = "#8a4517"
end = "#a53912"

[gradients.available]
start = "#6a5e50"
mid = "#006b3c"
end = "#005626"

[gradients.cached]
start = "#2d568c"
mid = "#006570"
end = "#00505c"

[gradients.free]
start = "#4c6257"
mid = "#006b3c"
end = "#005626"

[gradients.download]
start = "#2d568c"
mid = "#006570"
end = "#154178"

[gradients.upload]
start = "#89436e"
mid = "#8a4517"
end = "#732c59"

[gradients.gpu]
start = "#006b3c"
mid = "#765c00"
end = "#a53912"

[gradients.gpu_clock]
start = "#2d568c"
mid = "#006570"
end = "#00505c"

[gradients.gpu_power]
start = "#765c00"
mid = "#8a4517"
end = "#a53912"

[gradients.gpu_vram]
start = "#89436e"
mid = "#8a4517"
end = "#732c59"

[gradients.disk_read]
start = "#2d568c"
mid = "#006570"
end = "#154178"

[gradients.disk_write]
start = "#89436e"
mid = "#8a4517"
end = "#732c59"

[gradients.disk_busy]
start = "#765c00"
mid = "#8a4517"
end = "#a53912"

[gradients.temp]
start = "#2d568c"
mid = "#8a4517"
end = "#a53912"

[gradients.process]
start = "#006b3c"
mid = "#765c00"
end = "#a53912"
