[colors]
main_bg = "#e4e4e7"
main_fg = "#737680"
title = "#272a34"
hi_fg = "#909090"
selected_bg = "#b8174c"
selected_fg = "#ffffff"
graph_text = "#404040"
meter_bg = "#404040"
proc_tree_fg = "#404040"
cpu_box = "#367bf0"
mem_box = "#19a187"
net_box = "#fd3535"
proc_box = "#4aaee6"
gpu_box = "#e6a019"
disk_box = "#9b59b6"
help_box = "#367bf0"
options_box = "#e6a019"
proc_follow_bg = "#367bf0"
followed_bg = "#367bf0"
followed_fg = "#ffffff"

[gradients.temp]
start = "#367bf0"
mid = "#b8174c"
end = "#d41919"

[gradients.cpu_upper]
start = "#367bf0"
mid = "#4aaee6"
end = "#54bd8e"

[gradients.cpu_lower]
start = "#4897d4"
mid = "#5474e8"
end = "#ff40b6"

[gradients.free]
start = "#811035"
mid = "#b8174c"
end = "#d41919"

[gradients.cached]
start = "#2656a8"
mid = "#4aaee6"
end = "#23bac2"

[gradients.available]
start = "#fea44c"
mid = "#fd7d00"
end = "#fe7171"

[gradients.used]
start = "#12715f"
mid = "#19a187"
end = "#23bac2"

[gradients.download]
start = "#367bf0"
mid = "#19a187"
end = "#4aaee6"

[gradients.upload]
start = "#8c42ab"
mid = "#b8174c"
end = "#d41919"

[gradients.disk_read]
start = "#367bf0"
mid = "#19a187"
end = "#4aaee6"

[gradients.disk_write]
start = "#8c42ab"
mid = "#b8174c"
end = "#d41919"

[gradients.disk_busy]
start = "#12715f"
mid = "#19a187"
end = "#23bac2"

[gradients.process]
start = "#367bf0"
mid = "#4aaee6"
end = "#54bd8e"

[gradients.gpu]
start = "#367bf0"
mid = "#4aaee6"
end = "#54bd8e"

[gradients.gpu_clock]
start = "#00897b"
mid = "#00acc1"
end = "#26c6da"

[gradients.gpu_power]
start = "#fea44c"
mid = "#fd7d00"
end = "#fe7171"

[gradients.gpu_vram]
start = "#5c6bc0"
mid = "#7986cb"
end = "#9fa8da"

