[colors]
main_bg = "#100F0F"
main_fg = "#CECDC3"
title = "#FFFCF0"
hi_fg = "#DA702C"
selected_bg = "#403E3C"
selected_fg = "#FFFCF0"
graph_text = "#878580"
meter_bg = "#343331"
proc_tree_fg = "#575653"
cpu_box = "#4385BE"
mem_box = "#879A39"
net_box = "#CE5D97"
proc_box = "#3AA99F"
gpu_box = "#DA702C"
disk_box = "#8B7EC8"
help_box = "#4385BE"
options_box = "#DA702C"
proc_follow_bg = "#4385BE"
followed_bg = "#4385BE"
followed_fg = "#FFFCF0"

[gradients.temp]
start = "#4385BE"
mid = "#8B7EC8"
end = "#D14D41"

[gradients.cpu]
start = "#3AA99F"
mid = "#D0A215"
end = "#D14D41"

[gradients.free]
start = "#343331"
mid = "#575653"
end = "#879A39"

[gradients.cached]
start = "#205EA6"
mid = "#4385BE"
end = "#3AA99F"

[gradients.available]
start = "#AD8301"
mid = "#D0A215"
end = "#DA702C"

[gradients.used]
start = "#879A39"
mid = "#DA702C"
end = "#D14D41"

[gradients.download]
start = "#205EA6"
mid = "#4385BE"
end = "#3AA99F"

[gradients.upload]
start = "#A02F6F"
mid = "#CE5D97"
end = "#8B7EC8"

[gradients.disk_read]
start = "#205EA6"
mid = "#4385BE"
end = "#3AA99F"

[gradients.disk_write]
start = "#A02F6F"
mid = "#CE5D97"
end = "#8B7EC8"

[gradients.disk_busy]
start = "#879A39"
mid = "#DA702C"
end = "#D14D41"

[gradients.process]
start = "#879A39"
mid = "#D0A215"
end = "#D14D41"

[gradients.gpu]
start = "#3AA99F"
mid = "#D0A215"
end = "#D14D41"

[gradients.gpu_clock]
start = "#4385BE"
mid = "#3AA99F"
end = "#66CDAA"

[gradients.gpu_power]
start = "#DA702C"
mid = "#D0A215"
end = "#D14D41"

[gradients.gpu_vram]
start = "#8B7EC8"
mid = "#CE5D97"
end = "#D14D41"

