[colors]
main_bg = "#fbf1c7"
main_fg = "#3c3836"
title = "#3c3836"
hi_fg = "#cc241d"
graph_text = "#a89984"
meter_bg = "#ebdbb2"
selected_bg = "#f2e5bc"
selected_fg = "#8f3f71"
followed_bg = "#98971a"
followed_fg = "#8f3f71"
dead_proc_fg = "#9c947e"
cpu_widget = "#a89984"
mem_widget = "#a89984"
net_widget = "#a89984"
proc_widget = "#a89984"
gpu_widget = "#a89984"
disk_widget = "#a89984"
help_box = "#a89984"
options_box = "#a89984"
proc_tree_fg = "#ebdbb2"

statusbar_bg = "#fbf1c7"
statusbar_fg = "#3c3836"
statusbar_hi = "#cc241d"
statusbar_sep = "#a89984"

menu_fg = "#fbf1c7"
menu_hi_fg = "#ebdbb2"
[gradients.cpu_upper]
start = "#427b58"
mid = "#d79921"
end = "#cc241d"

[gradients.cpu_lower]
start = "#7c6f64"
mid = "#b16286"
end = "#8f3f71"

[gradients.used]
start = "#427b58"
mid = "#d65d0e"
end = "#cc241d"

[gradients.available]
start = "#cc241d"
mid = "#d65d0e"
end = "#b57614"

[gradients.cached]
start = "#458588"
mid = "#076678"
end = "#427b58"

[gradients.free]
start = "#cc241d"
mid = "#d79921"
end = "#427b58"

[gradients.download]
start = "#98971a"
mid = "#689d6a"
end = "#79740e"

[gradients.upload]
start = "#cc241d"
mid = "#d65d0e"
end = "#b57614"

[gradients.gpu]
start = "#427b58"
mid = "#d79921"
end = "#cc241d"

[gradients.gpu_clock]
start = "#458588"
mid = "#076678"
end = "#427b58"

[gradients.gpu_power]
start = "#d65d0e"
mid = "#d79921"
end = "#cc241d"

[gradients.gpu_vram]
start = "#b16286"
mid = "#8f3f71"
end = "#9d0006"

[gradients.disk_read]
start = "#98971a"
mid = "#689d6a"
end = "#79740e"

[gradients.disk_write]
start = "#cc241d"
mid = "#d65d0e"
end = "#b57614"

[gradients.disk_busy]
start = "#427b58"
mid = "#d65d0e"
end = "#cc241d"

[gradients.temp]
start = "#98971a"
mid = "#b25d1b"
end = "#cc241d"

[gradients.process]
start = "#427b58"
mid = "#af3a03"
end = "#cc241d"


