[colors]
main_bg = "#1C1E26"
main_fg = "#f8f8f2"
title = "#f8f8f2"
hi_fg = "#B877DB"
graph_text = "#f8f8f2"
meter_bg = "#272e33"
selected_bg = "#282b37"
selected_fg = "#f8f8f2"
followed_bg = "#27D796"
followed_fg = "#f8f8f2"
dead_proc_fg = "#8a8b8c"
cpu_widget = "#B877DB"
mem_widget = "#27D796"
net_widget = "#E95678"
proc_widget = "#25B2BC"
gpu_widget = "#E5C07B"
disk_widget = "#6C6F93"
help_box = "#26BBD9"
options_box = "#E5C07B"
proc_tree_fg = "#272e33"

statusbar_bg = "#1C1E26"
statusbar_fg = "#f8f8f2"
statusbar_hi = "#B877DB"
statusbar_sep = "#8a8b8c"

menu_fg = "#f8f8f2"
menu_hi_fg = "#b877db"
[gradients.cpu_upper]
start = "#27D796"
mid = "#FAC29A"
end = "#E95678"

[gradients.cpu_lower]
start = "#26bbd9"
mid = "#b877db"
end = "#6c6f93"

[gradients.used]
start = "#27D796"
mid = "#FAC29A"
end = "#E95678"

[gradients.available]
start = "#27D796"
mid = "#FAC29A"
end = "#E95678"

[gradients.cached]
start = "#27D796"
mid = "#FAC29A"
end = "#E95678"

[gradients.free]
start = "#E95678"
mid = "#FAC29A"
end = "#27D796"

[gradients.download]
start = "#27D796"
mid = "#FAC29A"
end = "#E95678"

[gradients.upload]
start = "#27D796"
mid = "#FAC29A"
end = "#E95678"

[gradients.gpu]
start = "#27D796"
mid = "#FAC29A"
end = "#E95678"

[gradients.gpu_clock]
start = "#25B2BC"
mid = "#59E1E3"
end = "#89F2F5"

[gradients.gpu_power]
start = "#FAB795"
mid = "#F09483"
end = "#E95678"

[gradients.gpu_vram]
start = "#B877DB"
mid = "#9B6BCD"
end = "#7C5FBF"

[gradients.disk_read]
start = "#27D796"
mid = "#FAC29A"
end = "#E95678"

[gradients.disk_write]
start = "#27D796"
mid = "#FAC29A"
end = "#E95678"

[gradients.disk_busy]
start = "#27D796"
mid = "#FAC29A"
end = "#E95678"

[gradients.temp]
start = "#27D796"
mid = "#FAC29A"
end = "#E95678"

[gradients.process]
start = "#27D796"
mid = "#FAC29A"
end = "#E95678"


