[colors]
main_bg = "#16161D"
main_fg = "#dcd7ba"
title = "#dcd7ba"
hi_fg = "#C34043"
graph_text = "#727169"
meter_bg = "#727169"
selected_bg = "#223249"
selected_fg = "#dca561"
followed_bg = "#7E9CDB"
followed_fg = "#dca561"
cpu_widget = "#727169"
mem_widget = "#727169"
net_widget = "#727169"
proc_widget = "#727169"
gpu_widget = "#727169"
disk_widget = "#727169"
help_box = "#727169"
options_box = "#727169"
proc_tree_fg = "#727169"

[gradients.cpu_upper]
start = "#98BB6C"
mid = "#DCA561"
end = "#E82424"

[gradients.cpu_lower]
start = "#7E9CDB"
mid = "#938AA9"
end = "#957FBB"

[gradients.used]
start = "#658594"
mid = "#7E9CDB"
end = "#7FB4CA"

[gradients.available]
start = "#938AA9"
mid = "#957FBB"
end = "#9CABCA"

[gradients.cached]
start = "#C0A36E"
mid = "#DCA561"
end = "#FF9E3B"

[gradients.free]
start = "#E82424"
mid = "#C34043"
end = "#FF5D62"

[gradients.download]
start = "#7E9CDB"
mid = "#938AA9"
end = "#957FBB"

[gradients.upload]
start = "#DCA561"
mid = "#E6C384"
end = "#E82424"

[gradients.gpu]
start = "#98BB6C"
mid = "#DCA561"
end = "#E82424"

[gradients.gpu_clock]
start = "#658594"
mid = "#7E9CDB"
end = "#7FB4CA"

[gradients.gpu_power]
start = "#DCA561"
mid = "#FF9E3B"
end = "#E82424"

[gradients.gpu_vram]
start = "#938AA9"
mid = "#957FBB"
end = "#9CABCA"

[gradients.disk_read]
start = "#7E9CDB"
mid = "#938AA9"
end = "#957FBB"

[gradients.disk_write]
start = "#DCA561"
mid = "#E6C384"
end = "#E82424"

[gradients.disk_busy]
start = "#658594"
mid = "#7E9CDB"
end = "#7FB4CA"

[gradients.temp]
start = "#98BB6C"
mid = "#DCA561"
end = "#E82424"

[gradients.process]
start = "#98BB6C"
mid = "#DCA561"
end = "#C34043"


