[colors]
main_bg = "#1b2224"
main_fg = "#F8F8F2"
title = "#F8F8F2"
hi_fg = "#2eb398"
graph_text = "#797667"
meter_bg = "#595647"
selected_bg = "#0d493d"
selected_fg = "#F8F8F2"
followed_bg = "#2d2042"
followed_fg = "#F8F8F2"
dead_proc_fg = "#595647"
cpu_widget = "#75715E"
mem_widget = "#75715E"
net_widget = "#75715E"
proc_widget = "#75715E"
gpu_widget = "#75715E"
disk_widget = "#75715E"
help_box = "#75715E"
options_box = "#75715E"
proc_tree_fg = "#595647"

statusbar_bg = "#1b2224"
statusbar_fg = "#F8F8F2"
statusbar_hi = "#2eb398"
statusbar_sep = "#797667"

[gradients.cpu_upper]
start = "#33b165"
mid = "#F8F8F2"
end = "#2eb398"

[gradients.cpu_lower]
start = "#75715E"
mid = "#66D9EF"
end = "#aae7f2"

[gradients.used]
start = "#75715E"
mid = "#2eb398"
end = "#33b165"

[gradients.available]
start = "#75715E"
mid = "#E6DB74"
end = "#f2ecb6"

[gradients.cached]
start = "#75715E"
mid = "#66D9EF"
end = "#aae7f2"

[gradients.free]
start = "#75715E"
mid = "#a9c474"
end = "#e2f5bc"

[gradients.download]
start = "#2d2042"
mid = "#2eb398"
end = "#33b165"

[gradients.upload]
start = "#0d493d"
mid = "#2eb398"
end = "#33b165"

[gradients.gpu]
start = "#33b165"
mid = "#F8F8F2"
end = "#2eb398"

[gradients.gpu_clock]
start = "#2eb398"
mid = "#66D9EF"
end = "#aae7f2"

[gradients.gpu_power]
start = "#E6DB74"
mid = "#f2ecb6"
end = "#FD971F"

[gradients.gpu_vram]
start = "#AE81FF"
mid = "#9b6bcd"
end = "#7c5fbf"

[gradients.disk_read]
start = "#2d2042"
mid = "#2eb398"
end = "#33b165"

[gradients.disk_write]
start = "#0d493d"
mid = "#2eb398"
end = "#33b165"

[gradients.disk_busy]
start = "#75715E"
mid = "#2eb398"
end = "#33b165"

[gradients.temp]
start = "#7976B7"
mid = "#D8B8B2"
end = "#33b165"

[gradients.process]
start = "#33b165"
mid = "#F8F8F2"
end = "#2eb398"


