[colors]
main_bg = "#060604"
main_fg = "#F8F8F2"
title = "#F8F8F2"
hi_fg = "#F92672"
graph_text = "#797667"
meter_bg = "#595647"
selected_bg = "#7a1137"
selected_fg = "#F8F8F2"
followed_bg = "#2d2042"
followed_fg = "#F8F8F2"
cpu_box = "#75715E"
mem_box = "#75715E"
net_box = "#75715E"
proc_box = "#75715E"
gpu_box = "#75715E"
disk_box = "#75715E"
help_box = "#75715E"
options_box = "#75715E"
proc_tree_fg = "#595647"

[gradients.cpu_upper]
start = "#A6E22E"
mid = "#F8F8F2"
end = "#F92672"

[gradients.cpu_lower]
start = "#4897d4"
mid = "#5474e8"
end = "#ff40b6"

[gradients.used]
start = "#75715E"
mid = "#F92672"
end = "#ff87b2"

[gradients.available]
start = "#75715E"
mid = "#E6DB74"
end = "#f2ecb6"

[gradients.cached]
start = "#75715E"
mid = "#66D9EF"
end = "#aae7f2"

[gradients.free]
start = "#75715E"
mid = "#a9c474"
end = "#e2f5bc"

[gradients.download]
start = "#2d2042"
mid = "#7352a8"
end = "#ccaefc"

[gradients.upload]
start = "#570d33"
mid = "#cf277d"
end = "#fa91c7"

[gradients.gpu]
start = "#A6E22E"
mid = "#F8F8F2"
end = "#F92672"

[gradients.gpu_clock]
start = "#66D9EF"
mid = "#aae7f2"
end = "#d0f0f8"

[gradients.gpu_power]
start = "#E6DB74"
mid = "#FD971F"
end = "#F92672"

[gradients.gpu_vram]
start = "#AE81FF"
mid = "#9b6bcd"
end = "#7c5fbf"

[gradients.disk_read]
start = "#2d2042"
mid = "#7352a8"
end = "#ccaefc"

[gradients.disk_write]
start = "#570d33"
mid = "#cf277d"
end = "#fa91c7"

[gradients.disk_busy]
start = "#75715E"
mid = "#F92672"
end = "#ff87b2"

[gradients.temp]
start = "#7976B7"
mid = "#D8B8B2"
end = "#F92672"

[gradients.process]
start = "#A6E22E"
mid = "#F8F8F2"
end = "#F92672"


