[colors]
main_bg = "#000000"
main_fg = "#ffa500"
data_label_fg = "#a66b00"
title = "#ffa500"
hi_fg = "#ffcc66"
graph_text = "#4d3200"
meter_bg = "#4d3200"
selected_bg = "#ffa500"
selected_fg = "#000000"
followed_bg = "#ffa500"
followed_fg = "#000000"
dead_proc_fg = "#805200"
cpu_widget = "#ffa500"
mem_widget = "#ffa500"
net_widget = "#ffa500"
proc_widget = "#ffa500"
gpu_widget = "#ffa500"
disk_widget = "#ffa500"
help_box = "#ffa500"
options_box = "#ffa500"
proc_tree_fg = "#4d3200"

statusbar_bg = "#000000"
statusbar_fg = "#ffa500"
statusbar_hi = "#ffcc66"
statusbar_sep = "#805200"

[gradients.cpu_upper]
start = "#996300"
mid = "#cc8400"
end = "#ffa500"

[gradients.cpu_lower]
start = "#3d1900"
mid = "#663300"
end = "#996633"

[gradients.used]
start = "#996300"
mid = "#cc8400"
end = "#ffa500"

[gradients.available]
start = "#996300"
mid = "#cc8400"
end = "#ffa500"

[gradients.cached]
start = "#996300"
mid = "#cc8400"
end = "#ffa500"

[gradients.free]
start = "#996300"
mid = "#cc8400"
end = "#ffa500"

[gradients.download]
start = "#996300"
mid = "#cc8400"
end = "#ffa500"

[gradients.upload]
start = "#996300"
mid = "#cc8400"
end = "#ffa500"

[gradients.gpu]
start = "#996300"
mid = "#cc8400"
end = "#ffa500"

[gradients.gpu_clock]
start = "#805300"
mid = "#a06800"
end = "#cc8400"

[gradients.gpu_power]
start = "#cc4400"
mid = "#e66000"
end = "#ff8000"

[gradients.gpu_vram]
start = "#7a5000"
mid = "#b37400"
end = "#e69500"

[gradients.disk_read]
start = "#996300"
mid = "#cc8400"
end = "#ffa500"

[gradients.disk_write]
start = "#996300"
mid = "#cc8400"
end = "#ffa500"

[gradients.disk_busy]
start = "#996300"
mid = "#cc8400"
end = "#ffa500"

[gradients.temp]
start = "#996300"
mid = "#cc8400"
end = "#ffa500"

[gradients.process]
start = "#996300"
mid = "#cc8400"
end = "#ffa500"


