[colors]
main_bg = "#F2EEDE"
main_fg = "#000000"
data_label_fg = "#55534e"
title = "#000000"
hi_fg = "#CC3E28"
graph_text = "#d8d5c7"
meter_bg = "#d8d5c7"
selected_bg = "#D8D5C7"
selected_fg = "#000000"
followed_bg = "#555555"
followed_fg = "#000000"
dead_proc_fg = "#79776f"
cpu_widget = "#000000"
mem_widget = "#000000"
net_widget = "#000000"
proc_widget = "#000000"
gpu_widget = "#000000"
disk_widget = "#000000"
help_box = "#000000"
options_box = "#000000"
proc_tree_fg = "#d8d5c7"

statusbar_bg = "#F2EEDE"
statusbar_fg = "#000000"
statusbar_hi = "#CC3E28"
statusbar_sep = "#79776f"

[gradients.cpu_upper]
start = "#555555"
mid = "#000000"
end = "#CC3E28"

[gradients.cpu_lower]
start = "#1e6fcc"
mid = "#6f87a3"
end = "#1e3866"

[gradients.used]
start = "#CC3E28"
mid = "#cc3e28"
end = "#CC3E28"

[gradients.available]
start = "#216609"
mid = "#216609"
end = "#216609"

[gradients.cached]
start = "#1e6fcc"
mid = "#1e6fcc"
end = "#1e6fcc"

[gradients.free]
start = "#216609"
mid = "#216609"
end = "#216609"

[gradients.download]
start = "#555555"
mid = "#000000"
end = "#CC3E28"

[gradients.upload]
start = "#555555"
mid = "#000000"
end = "#CC3E28"

[gradients.gpu]
start = "#555555"
mid = "#000000"
end = "#CC3E28"

[gradients.gpu_clock]
start = "#1e6fcc"
mid = "#1858a6"
end = "#124280"

[gradients.gpu_power]
start = "#CC3E28"
mid = "#a03020"
end = "#802418"

[gradients.gpu_vram]
start = "#5c21a5"
mid = "#7830cc"
end = "#9440f0"

[gradients.disk_read]
start = "#555555"
mid = "#000000"
end = "#CC3E28"

[gradients.disk_write]
start = "#555555"
mid = "#000000"
end = "#CC3E28"

[gradients.disk_busy]
start = "#CC3E28"
mid = "#cc3e28"
end = "#CC3E28"

[gradients.temp]
start = "#555555"
mid = "#000000"
end = "#CC3E28"

[gradients.process]
start = "#555555"
mid = "#000000"
end = "#CC3E28"


