[colors]
main_bg = "#1a1b26"
main_fg = "#cfc9c2"
title = "#cfc9c2"
hi_fg = "#7dcfff"
graph_text = "#565f89"
meter_bg = "#565f89"
selected_bg = "#414868"
selected_fg = "#cfc9c2"
followed_bg = "#00ff00"
followed_fg = "#cfc9c2"
cpu_box = "#565f89"
mem_box = "#565f89"
net_box = "#565f89"
proc_box = "#565f89"
gpu_box = "#565f89"
disk_box = "#565f89"
help_box = "#565f89"
options_box = "#565f89"
proc_tree_fg = "#565f89"
proc_follow_bg = "#00ff00"

[gradients.cpu_upper]
start = "#00ff00"
mid = "#ccff66"
end = "#ff0000"

[gradients.cpu_lower]
start = "#4897d4"
mid = "#5474e8"
end = "#ff40b6"

[gradients.used]
start = "#00ff00"
mid = "#ccff66"
end = "#ff0000"

[gradients.available]
start = "#ff0000"
mid = "#ccff66"
end = "#00ff00"

[gradients.cached]
start = "#00ff00"
mid = "#ccff66"
end = "#ff0000"

[gradients.free]
start = "#ff0000"
mid = "#ccff66"
end = "#00ff00"

[gradients.download]
start = "#00ff00"
mid = "#ff9933"
end = "#ff0000"

[gradients.upload]
start = "#00ff00"
mid = "#ff9933"
end = "#ff0000"

[gradients.gpu]
start = "#00ff00"
mid = "#ccff66"
end = "#ff0000"

[gradients.gpu_clock]
start = "#00ccff"
mid = "#66ddff"
end = "#99eeff"

[gradients.gpu_power]
start = "#ff9933"
mid = "#ff6600"
end = "#ff0000"

[gradients.gpu_vram]
start = "#9966ff"
mid = "#bb88ff"
end = "#cc99ff"

[gradients.disk_read]
start = "#00ff00"
mid = "#ff9933"
end = "#ff0000"

[gradients.disk_write]
start = "#00ff00"
mid = "#ff9933"
end = "#ff0000"

[gradients.disk_busy]
start = "#00ff00"
mid = "#ccff66"
end = "#ff0000"

[gradients.temp]
start = "#00ff00"
mid = "#ff9933"
end = "#ff0000"

[gradients.process]
start = "#9999ff"
mid = "#4d4dff"
end = "#a64dff"

