[colors]
main_bg = "#fdf6e3"
main_fg = "#586e75"
title = "#002b36"
hi_fg = "#b58900"
selected_bg = "#eee8d5"
selected_fg = "#b58900"
graph_text = "#eee8d5"
meter_bg = "#eee8d5"
proc_tree_fg = "#eee8d5"
cpu_box = "#93a1a1"
mem_box = "#93a1a1"
net_box = "#93a1a1"
proc_box = "#93a1a1"
gpu_box = "#93a1a1"
disk_box = "#93a1a1"
help_box = "#93a1a1"
options_box = "#93a1a1"
proc_follow_bg = "#3d4070"
followed_bg = "#3d4070"
followed_fg = "#b58900"

[gradients.temp]
start = "#268bd2"
mid = "#ccb5f7"
end = "#fc5378"

[gradients.cpu_upper]
start = "#adc700"
mid = "#d6a200"
end = "#e65317"

[gradients.cpu_lower]
start = "#4897d4"
mid = "#5474e8"
end = "#ff40b6"

[gradients.free]
start = "#4e5900"
mid = "#849700"
end = "#bad600"

[gradients.cached]
start = "#114061"
mid = "#1b6599"
end = "#268bd2"

[gradients.available]
start = "#705500"
mid = "#ae8400"
end = "#edb400"

[gradients.used]
start = "#6e1718"
mid = "#a72324"
end = "#e02f30"

[gradients.download]
start = "#3d4070"
mid = "#6c71c4"
end = "#a3a8f7"

[gradients.upload]
start = "#701c45"
mid = "#d33682"
end = "#f56caf"

[gradients.disk_read]
start = "#3d4070"
mid = "#6c71c4"
end = "#a3a8f7"

[gradients.disk_write]
start = "#701c45"
mid = "#d33682"
end = "#f56caf"

[gradients.disk_busy]
start = "#6e1718"
mid = "#a72324"
end = "#e02f30"

[gradients.process]
start = "#adc700"
mid = "#d6a200"
end = "#e65317"

[gradients.gpu]
start = "#adc700"
mid = "#d6a200"
end = "#e65317"

[gradients.gpu_clock]
start = "#268bd2"
mid = "#2aa198"
end = "#859900"

[gradients.gpu_power]
start = "#cb4b16"
mid = "#d6a200"
end = "#e65317"

[gradients.gpu_vram]
start = "#6c71c4"
mid = "#d33682"
end = "#dc322f"

