[colors]
main_bg = "#002b36"
main_fg = "#eee8d5"
title = "#fdf6e3"
hi_fg = "#b58900"
graph_text = "#073642"
meter_bg = "#073642"
selected_bg = "#073642"
selected_fg = "#d6a200"
followed_bg = "#3d4070"
followed_fg = "#d6a200"
dead_proc_fg = "#778a86"
cpu_widget = "#586e75"
mem_widget = "#586e75"
net_widget = "#586e75"
proc_widget = "#586e75"
gpu_widget = "#586e75"
disk_widget = "#586e75"
help_box = "#586e75"
options_box = "#586e75"
proc_tree_fg = "#073642"

[gradients.cpu_upper]
start = "#adc700"
mid = "#d6a200"
end = "#e65317"

[gradients.cpu_lower]
start = "#3d4070"
mid = "#6c71c4"
end = "#a3a8f7"

[gradients.used]
start = "#6e1718"
mid = "#a72324"
end = "#e02f30"

[gradients.available]
start = "#705500"
mid = "#ae8400"
end = "#edb400"

[gradients.cached]
start = "#114061"
mid = "#1b6599"
end = "#268bd2"

[gradients.free]
start = "#4e5900"
mid = "#849700"
end = "#bad600"

[gradients.download]
start = "#3d4070"
mid = "#6c71c4"
end = "#a3a8f7"

[gradients.upload]
start = "#701c45"
mid = "#d33682"
end = "#f56caf"

[gradients.gpu]
start = "#adc700"
mid = "#d6a200"
end = "#e65317"

[gradients.gpu_clock]
start = "#268bd2"
mid = "#2aa198"
end = "#859900"

[gradients.gpu_power]
start = "#cb4b16"
mid = "#d6a200"
end = "#e65317"

[gradients.gpu_vram]
start = "#6c71c4"
mid = "#d33682"
end = "#dc322f"

[gradients.disk_read]
start = "#3d4070"
mid = "#6c71c4"
end = "#a3a8f7"

[gradients.disk_write]
start = "#701c45"
mid = "#d33682"
end = "#f56caf"

[gradients.disk_busy]
start = "#6e1718"
mid = "#a72324"
end = "#e02f30"

[gradients.temp]
start = "#268bd2"
mid = "#ccb5f7"
end = "#fc5378"

[gradients.process]
start = "#adc700"
mid = "#d6a200"
end = "#e65317"


