[colors]
main_bg = "#24283b"
main_fg = "#cfc9c2"
title = "#cfc9c2"
hi_fg = "#7dcfff"
graph_text = "#565f89"
meter_bg = "#565f89"
selected_bg = "#414868"
selected_fg = "#cfc9c2"
followed_bg = "#9ece6a"
followed_fg = "#cfc9c2"
cpu_widget = "#565f89"
mem_widget = "#565f89"
net_widget = "#565f89"
proc_widget = "#565f89"
gpu_widget = "#565f89"
disk_widget = "#565f89"
help_box = "#565f89"
options_box = "#565f89"
proc_tree_fg = "#565f89"

[gradients.cpu_upper]
start = "#9ece6a"
mid = "#e0af68"
end = "#f7768e"

[gradients.cpu_lower]
start = "#4897d4"
mid = "#5474e8"
end = "#ff40b6"

[gradients.used]
start = "#9ece6a"
mid = "#e0af68"
end = "#f7768e"

[gradients.available]
start = "#9ece6a"
mid = "#e0af68"
end = "#f7768e"

[gradients.cached]
start = "#9ece6a"
mid = "#e0af68"
end = "#f7768e"

[gradients.free]
start = "#9ece6a"
mid = "#e0af68"
end = "#f7768e"

[gradients.download]
start = "#9ece6a"
mid = "#e0af68"
end = "#f7768e"

[gradients.upload]
start = "#9ece6a"
mid = "#e0af68"
end = "#f7768e"

[gradients.gpu]
start = "#9ece6a"
mid = "#e0af68"
end = "#f7768e"

[gradients.gpu_clock]
start = "#7aa2f7"
mid = "#7dcfff"
end = "#89ddff"

[gradients.gpu_power]
start = "#ff9e64"
mid = "#f7768e"
end = "#db4b4b"

[gradients.gpu_vram]
start = "#bb9af7"
mid = "#9d7cd8"
end = "#7f63c4"

[gradients.disk_read]
start = "#9ece6a"
mid = "#e0af68"
end = "#f7768e"

[gradients.disk_write]
start = "#9ece6a"
mid = "#e0af68"
end = "#f7768e"

[gradients.disk_busy]
start = "#9ece6a"
mid = "#e0af68"
end = "#f7768e"

[gradients.temp]
start = "#9ece6a"
mid = "#e0af68"
end = "#f7768e"

[gradients.process]
start = "#9ece6a"
mid = "#e0af68"
end = "#f7768e"


